[features]
seeds = false
skip-lint = false
[programs.localnet]
craffles = "cRafa563zLryDbGePsXaKEHkcY7nSScjszMxh1UjiTJ"
[programs.devnet]
craffles = "cRafa563zLryDbGePsXaKEHkcY7nSScjszMxh1UjiTJ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/edujlac/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
